---
title: "exp-redo"
author: "Allen Yeh"
output:
  html_document
---

```
```

```{r warning=FALSE}
library(tidyverse)
library(gmodels)
library(rstatix)
```

### Import data

#### Read the csv file and claim the data type
```{r}
fitered_run_ids <- c("0", "2", "6", "8", "9", "12", "13", "14", "19", "20", "24", "25", "31")
run_ids <- c("1", "3", "4", "5", "7", "10", "11", "15", "16", "17", "18", "21", "22", "23", "26", "27", "29", "30")

gesture_level <- c("SHIFT_ABD", "SHIFT_ADD", "SPIN_ABD_HALF", "SPIN_ABD_FULL", "SPIN_ADD_HALF", "SPIN_ADD_FULL", "ROTATE_ABD_HALF", "ROTATE_ABD_FULL", "ROTATE_ADD_HALF", "ROTATE_ADD_FULL", "FLIP_ABD_HALF", "FLIP_ABD_FULL", "FLIP_ADD_HALF", "FLIP_ADD_FULL")

redo <- read_csv("summary_redo.csv", col_types = cols(
  gesture = col_factor(levels = gesture_level), 
  manipulation = col_factor(levels = c("0", "1", "2", "3")), 
  direction = col_factor(levels = c("0", "1")),
  magnitude = col_factor(levels = c("0", "1", "2")),
  Reason_1 = col_integer(),
  Reason_2 = col_integer(),
  Reason_3 = col_integer(),
  Reason_4 = col_integer(),
  Reason_5 = col_integer()
  )) %>% 
  filter(tolower(`id`) %in% run_ids) %>%
  mutate(
    manipulation_code = manipulation %>% recode_factor(
      `3` = "FLIP",  
      `2` = "ROTATE",
      `1` = "SPIN",
      `0` = "SHIFT"
      ),
    direction_code = direction %>% recode_factor(
      `1` = "ADD",
      `0` = "ABD"
      ),
    magnitude_code = magnitude %>% recode_factor(
      `2` = "NONE",
      `1` = "FULL",
      `0` = "HALF"
      ),
  )

redo_count <- aggregate(cbind(redo$Reason_1, redo$Reason_2, redo$Reason_3, redo$Reason_4, redo$Reason_5), by=list(gesture=redo$gesture), FUN=sum)
redo_count_type <- aggregate(cbind(redo$Reason_1, redo$Reason_2, redo$Reason_3, redo$Reason_4, redo$Reason_5), by=list(gesture=redo$manipulation_code), FUN=sum)
redo_count_id <- aggregate(cbind(redo$Reason_1, redo$Reason_2, redo$Reason_3, redo$Reason_4, redo$Reason_5), by=list(gesture=redo$id), FUN=sum)

redo_count
redo_count_type
redo_count_id
```



