---
title: "exp time"
author: "Allen Yeh"
output:
  html_document: default
  pdf_document: default
---

```
```

```{r warning=FALSE}
library(tidyverse)
library(gmodels)
library(rstatix)
library(ggplot2)
```

### Import data

#### Read the csv file and claim the data type
```{r}
fitered_run_ids <- c("0", "2", "6", "8", "9", "12", "13", "14", "19", "20", "24", "25", "31")
run_ids <- c("1", "3", "4", "5", "7", "10", "11", "15", "16", "17", "18", "21", "22", "23", "26", "27", "29", "30")

gesture_level <- c("SHIFT_ABD", "SHIFT_ADD", "SPIN_ABD_HALF", "SPIN_ABD_FULL", "SPIN_ADD_HALF", "SPIN_ADD_FULL", "ROTATE_ABD_HALF", "ROTATE_ABD_FULL", "ROTATE_ADD_HALF", "ROTATE_ADD_FULL", "FLIP_ABD_HALF", "FLIP_ABD_FULL", "FLIP_ADD_HALF", "FLIP_ADD_FULL")

data <- read_csv("summary.csv", col_types = cols(
  gesture = col_factor(levels = gesture_level),
  manipulation = col_factor(levels = c("0", "1", "2", "3")), 
  direction = col_factor(levels = c("0", "1")),
  magnitude = col_factor(levels = c("0", "1", "2")),
  trial = col_integer(),
  time = col_integer(),
  x = col_double(),
  y = col_double(),
  z = col_double()
))  %>% 
  filter(tolower(`id`) %in% run_ids) %>% rowwise() %>%
  mutate(
    time_s = time/1000,
    manipulation_code = manipulation %>% recode_factor(
      `3` = "FLIP",  
      `2` = "ROTATE",
      `1` = "SPIN",
      `0` = "SHIFT"
      ),
    direction_code = direction %>% recode_factor(
      `1` = "ADD",
      `0` = "ABD"
      ),
    magnitude_code = magnitude %>% recode_factor(
      `2` = "NONE",
      `1` = "FULL",
      `0` = "HALF"
      ),
    main_axis = ifelse(manipulation_code == "FLIP", x, ifelse(manipulation_code == "ROTATE", y, ifelse(manipulation_code == "SPIN", z, 0))),
    main_axis_abs = abs(main_axis),
    second_axis = ifelse(manipulation_code == "FLIP", max(abs(y),abs(z)), ifelse(manipulation_code == "ROTATE",  max(abs(x),abs(z)), ifelse(manipulation_code == "SPIN",max(abs(x),abs(y)), 0))),

)

participants <- read_csv("exp_participants_short_v2.csv", col_types = cols(
  id = col_integer(),
  gender = col_factor(levels = c("Male","Female")), 
  age = col_integer(), 
  phoneExperience = col_factor(levels = c("-3","3-5", "6-10", "10-")),
  screenSize = col_factor(levels = c("-4", "4-5", "5-6", "6-")), 
  dailyUsage = col_factor(levels = c("-1", "1-2", "2-4", "4-8", "8-")), 
  handSize = col_factor(levels = c("5.5-6.5", "6.5-7.5", "7.5-8.5", "8.5-9.5", "9.5-10.5")),
  phoneHeight = col_double(),
  phoneWidth = col_double(),
  phoneThickness = col_double(),
  phoneWeight = col_double()
)) %>%
    filter(tolower(`id`) %in% run_ids) %>% 
  mutate(
    phoneSize_Num = screenSize  %>%  recode(
          "-4" = 1,
          "4-5" = 2,
          "5-6" = 3,
          "6-" = 4
          ),
    handSize_Num = handSize  %>%  recode(
          "5.5-6.5" = 1,
          "6.5-7.5" = 2,
          "7.5-8.5" = 3,
          "8.5-9.5" = 4,
          "9.5-10.5" = 5
          )
      )
```

### Recognizer
```{r warning=FALSE}
#time outlier
dataTime_filter <- data %>%
    filter(id == -1)

for (i in run_ids) {
  for (j in gesture_level){
    dataUser <- data %>%
      filter(id == i & gesture == j)
    
    Q <- quantile(dataUser$time_s, probs=c(.25, .75), na.rm = FALSE)
    iqr <- IQR(dataUser$time_s)
  
    eliminated<- subset(dataUser, dataUser$time_s > (Q[1] - 1.5*iqr) & dataUser$time_s < (Q[2]+1.5*iqr))
    dataTime_filter <- full_join(dataTime_filter, eliminated)
  }
}

dataTime_filter

time_filter <- setdiff(data,dataTime_filter)

h <- hist(time_filter$trial)
h

total_time <- full_join(dataTime_filter, participants)

nrow(total_time)

res <- cor.test(total_time$phoneSize_Num, total_time$time_s, 
                    method = "spearman")
res

res <- cor.test(total_time$handSize_Num, total_time$time_s, 
                    method = "spearman")
res

res <- cor.test(total_time$phoneHeight, total_time$time_s, 
                    method = "spearman")
res

res <- cor.test(total_time$phoneWidth, total_time$time_s, 
                    method = "spearman")
res

res <- cor.test(total_time$phoneThickness, total_time$time_s, 
                    method = "spearman")
res

res <- cor.test(total_time$phoneWeight, total_time$time_s, 
                    method = "spearman")
res

library("ggpubr")
ggscatter(total_time, x = "phoneSize_Num", y = "time_s", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "PhoneSize", ylab = "Time")

ggscatter(total_time, x = "handSize_Num", y = "time_s", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "HandSize", ylab = "Time")

ggscatter(total_time, x = "phoneHeight", y = "time_s", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "PhoneHeight", ylab = "Time")

ggscatter(total_time, x = "phoneWidth", y = "time_s", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "PhoneWidth", ylab = "Time")

ggscatter(total_time, x = "phoneThickness", y = "time_s", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "PhoneThickness", ylab = "Time")

ggscatter(total_time, x = "phoneWeight", y = "time_s", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "PhoneWeight", ylab = "Time")


```

### Time 

### Last three trial
```{r warning=FALSE}
data_user_summary <-dataTime_filter %>%
  group_by(id) %>%
  summarize(
    meanTime = time_s %>% mean(na.rm=TRUE),
    lowCI = ci(time_s)[2]%>% pmax(0),
    highCI = ci(time_s)[3],
    sd = ci(time_s)[4],
    std = time_s %>% sd())

fast_ids <- c("11", "4", "18")

data_user_gesture_summary <-dataTime_filter %>%
  filter(id %in% fast_ids) %>%
  group_by(gesture) %>%
  summarize(
    meanTime = time_s %>% mean(na.rm=TRUE),
    lowCI = ci(time_s)[2]%>% pmax(0),
    highCI = ci(time_s)[3],
    sd = ci(time_s)[4],
    std = time_s %>% sd())

data_user_manipulation_summary <-dataTime_filter %>%
  filter(id %in% fast_ids) %>%
  group_by(manipulation_code) %>%
  summarize(
    meanTime = time_s %>% mean(na.rm=TRUE),
    lowCI = ci(time_s)[2]%>% pmax(0),
    highCI = ci(time_s)[3],
    sd = ci(time_s)[4],
    std = time_s %>% sd())
```

#### summarize

```{r warning=FALSE}

boxplot(time_s~gesture,data=dataTime_filter, main="Time",
   xlab="Gesture", ylab="Time (s)", horizontal=TRUE, outline = FALSE)

data_summary <-dataTime_filter %>%
  group_by(gesture) %>%
  summarize(
    meanTime = time_s %>% mean(na.rm=TRUE),
    lowCITime = ci(time_s)[2]%>% pmax(0),
    highCITime = ci(time_s)[3],
    sdTime = ci(time_s)[4],
    stdTime = time_s %>% sd())

# line + dot
time_graph <- ggplot(data_summary) +
  geom_pointrange( aes(x=reorder(gesture, desc(gesture)), y=meanTime, ymin=lowCITime, ymax=highCITime), colour="orange", alpha=0.9, size=0.8) +
  scale_y_continuous(limits=c(1.5,5.5)) +
  coord_flip()

time_graph + theme( # remove the vertical grid lines
          panel.background = element_blank(),
          panel.grid.major.y = element_blank() ,
          # explicitly set the horizontal lines (or they will disappear too)
          panel.grid.major.x = element_line( size=.1, color="gray" ),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y=element_blank()
    )
ggsave("time_gesture_ci.pdf", width = 7, height = 7)

data_type_summary <-dataTime_filter %>%
  group_by(manipulation_code) %>%
  summarize(
    meanTime = time_s %>% mean(na.rm=TRUE),
    lowCI = ci(time_s)[2]%>% pmax(0),
    highCI = ci(time_s)[3],
    sd = ci(time_s)[4],
    std = time_s %>% sd())

# line + dot
time_type_graph <- ggplot(data_type_summary) +
  geom_pointrange( aes(x=manipulation_code, y=meanTime, ymin=lowCI, ymax=highCI), colour="orange", alpha=0.9, size=0.8) +
  scale_y_continuous(limits=c(1.5,5.5)) +
  coord_flip()

time_type_graph + theme( # remove the vertical grid lines
          panel.background = element_blank(),
          panel.grid.major.y = element_blank() ,
          # explicitly set the horizontal lines (or they will disappear too)
          panel.grid.major.x = element_line( size=.1, color="gray" ),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y=element_blank()
    )
ggsave("time_manipulation_ci.pdf", width = 7, height = 2)

data_type_summary

data_direction_summary <-dataTime_filter %>%
  group_by(direction_code) %>%
  summarize(
    meanTime = time_s %>% mean(na.rm=TRUE),
    lowCI = ci(time_s)[2]%>% pmax(0),
    highCI = ci(time_s)[3],
    sd = ci(time_s)[4],
    std = time_s %>% sd())

data_direction_summary

```

### manipulation x direction

```{r warning=FALSE}
data_md_summary <-dataTime_filter %>%
  group_by(manipulation_code, direction_code) %>%
  summarize(
    meanTime = time_s %>% mean(na.rm=TRUE),
    lowCI = ci(time_s)[2]%>% pmax(0),
    highCI = ci(time_s)[3],
    sd = ci(time_s)[4],
    std = time_s %>% sd())

data_md_summary
```

#### analysis
```{r warning=FALSE}
shapiro.test(dataTime_filter$time_s)

qqnorm(dataTime_filter$time_s); qqline(dataTime_filter$time_s, col = 2)
qqplot(dataTime_filter$time_s, rt(300, df = 5))

library(rcompanion)

plotNormalHistogram(dataTime_filter$time_s)

dataTime_filter$time_turkey =
     transformTukey(dataTime_filter$time_s,
                     plotit=FALSE)

plotNormalHistogram(dataTime_filter$time_turkey)

qqnorm(dataTime_filter$time_turkey); qqline(dataTime_filter$time_turkey, col = 2)
qqplot(dataTime_filter$time_turkey, rt(300, df = 5))

library("ez")
ezANOVA(dataTime_filter, dv=.(time_turkey), wid=.(id), within=.(manipulation_code, direction_code))

```

#### pairwise comparisons

```{r}
pairwise.t.test(dataTime_filter$time_turkey, dataTime_filter$manipulation_code, p.adjust="bonf")

pairwise.t.test(dataTime_filter$time_turkey, interaction(dataTime_filter$manipulation_code, dataTime_filter$direction_code), p.adjust="bonf")
```
### manipulation x direction x magnitude

```{r warning=FALSE}
data_anova = dataTime_filter %>%
    filter(manipulation_code != "SHIFT")

data_anova_summary <-data_anova %>%
  group_by(manipulation_code, direction_code, magnitude_code) %>%
  summarize(
    meanTime = time_s %>% mean(na.rm=TRUE),
    lowCI = ci(time_s)[2]%>% pmax(0),
    highCI = ci(time_s)[3],
    sd = ci(time_s)[4],
    std = time_s %>% sd())

data_anova_summary

data_anova_manipulation_summary <-data_anova %>%
  group_by(manipulation_code) %>%
  summarize(
    meanTime = time_s %>% mean(na.rm=TRUE),
    lowCI = ci(time_s)[2]%>% pmax(0),
    highCI = ci(time_s)[3],
    sd = ci(time_s)[4],
    std = time_s %>% sd())

data_anova_manipulation_summary

data_anova_direction_summary <-data_anova %>%
  group_by(direction_code) %>%
  summarize(
    meanTime = time_s %>% mean(na.rm=TRUE),
    lowCI = ci(time_s)[2]%>% pmax(0),
    highCI = ci(time_s)[3],
    sd = ci(time_s)[4],
    std = time_s %>% sd())

data_anova_direction_summary

data_anova_mag_summary <-data_anova %>%
  group_by(magnitude_code) %>%
  summarize(
    meanTime = time_s %>% mean(na.rm=TRUE),
    lowCI = ci(time_s)[2]%>% pmax(0),
    highCI = ci(time_s)[3],
    sd = ci(time_s)[4],
    std = time_s %>% sd())

data_anova_mag_summary

data_anova_md_summary <-data_anova %>%
  group_by(manipulation_code, direction_code) %>%
  summarize(
    meanTime = time_s %>% mean(na.rm=TRUE),
    lowCI = ci(time_s)[2]%>% pmax(0),
    highCI = ci(time_s)[3],
    sd = ci(time_s)[4],
    std = time_s %>% sd())

data_anova_md_summary
```


#### analysis
```{r warning=FALSE}
shapiro.test(data_anova$time_s)

library(rcompanion)

plotNormalHistogram(data_anova$time_s)

data_anova$time_turkey =
     transformTukey(data_anova$time_s,
                     plotit=FALSE)

plotNormalHistogram(data_anova$time_turkey)

qqnorm(data_anova$time_turkey); qqline(data_anova$time_turkey, col = 2)
qqplot(data_anova$time_turkey, rt(300, df = 5))

library("ez")
ezANOVA(data_anova, dv=.(time_turkey), wid=.(id), within=.(manipulation_code, direction_code, magnitude_code))

```
#### pairwise comparisons

```{r}
pairwise.t.test(data_anova$time_turkey, data_anova$manipulation_code, p.adjust="bonf")

pairwise.t.test(data_anova$time_turkey, data_anova$direction_code, p.adjust="bonf")

pairwise.t.test(data_anova$time_turkey, data_anova$magnitude_code, p.adjust="bonf")

pairwise.t.test(data_anova$time_turkey, interaction(data_anova$manipulation_code, data_anova$direction_code, data_anova$magnitude_code), p.adjust="bonf")
```

